### ISSUE TITLE
Option to download source language file from OneSky

### ISSUE THREAD

**Issue by xsveda** [onesky/plugin-intellij#2]
This plugin currently allows to upload any strings file to OneSky and to download any translation but there is no option to download source language file.
In my project I would like to move all the strings management to OneSky as people from marketing team would like to have access to all string from all languages. Then source language files and translations will be downloaded from OneSky before every app build so they are always up-to-date.
What do you think about such feature?
Anyway, thank you for this plugin, it is a great help!!!

**Comment by bretdabaker** [comment]
Sounds good and thanks for providing the use case, I will work on it this week.

**Comment by bretdabaker** [comment]
Added base language download: https://plugins.jetbrains.com/update/index?pr=&updateId=19894

**Comment by xsveda** [comment]
Works great, thanks!
