### ISSUE TITLE
No string files found for module

### ISSUE THREAD

**Issue by scana** [onesky/plugin-intellij#3]
Hi.
I was really happy when I've found out that you guys have made a plugin for AS, but unfortunately I was not able to make it work.

![zrzut ekranu 2015-05-26 16 40 21](https://cloud.githubusercontent.com/assets/1139325/7815019/1ef3b500-03c6-11e5-9111-dadc7cc0aa2c.png)

Got a couple of modules (app is a main module with the application itself), also, we have a lots of different flavours.
Any idea why the plugin does not display anything?

**Comment by bretdabaker** [comment]
@scana Have you tried selecting other modules? If you right-click the strings.xml file, you should see the OneSky menu and can send the file to OneSky. If it's greyed-out/disabled it means the module that the file belongs is not the same module you have selected in Settings.

**Comment by sugoi-wada** [comment]
In my case, I can select strings.xml file in "values-ja" or "values-es" directory. But I can't select (it means grayed-out/disabled) strings.xml file in default "values" directory.

**Comment by bretdabaker** [comment]
@sugoi-wada @scana I have tried to reproduce the bug with a multi module/flavour project but without luck. 

When you right click the default `values/strings.xml` menu, do you see a menu item named `Make Module '<Module Name>'`? If so what's `<Module Name>`? Does it match the project settings?

It would be great if you can provide a stripped-down version of your project that can reproduce the bug.

Thanks for your time!

**Comment by zoopolitic** [comment]
@bretdabaker have the same issue, made everything according to the tutorial, but strings list is empty.

**Comment by scana** [comment]
@bretdabaker hey, sorry for the delay.
No, I can't really see the ability to build (make) module, while right-clicking on strings.xml file.
I'll try to provide you a sample, but I'm afraid that it's gonna take some time.

EDIT:
the funny thing is that I can sync those files from OneSky without any problems

**Comment by zoopolitic** [comment]
@bretdabaker actually if I do everything like described in the tutorial - strings -> right click -> send strings then there is no strings. But also there is menu item OneSky(I'm on Mac OS) - and if I click "Send strings" from there - everything is fine.

**Comment by bretdabaker** [comment]
This is fixed in [1.3.5](https://plugins.jetbrains.com/update/index?pr=&updateId=22734)

Please try and see if it works.

**Comment by scana** [comment]
@bretdabaker Thanks!
I confirm that it's working now.
Fun fact - it had been working for some time - like a couple of weeks and then it suddenly stopped.
