### ISSUE TITLE
localizable.xml base language is overwritten with the Spanish language version

### ISSUE THREAD

**Issue by IAmMalte** [onesky/plugin-intellij#4]
Observed behaviour:
- Synchronising languages (sv, da, fr, it, nl, es, pt-BR, es, de) replaces our base language.xml with the Spanish content

Desired behaviour:
- Put Spanish into the right subfolder

**Comment by bretdabaker** [comment]
Thanks for the bug report. Fixed at [v1.3.1](https://plugins.jetbrains.com/update/index?pr=&updateId=20539).
