### ISSUE TITLE
IncorrectOperationException: "Cannot create file" when trying to sync strings

### ISSUE THREAD

**Issue by IAmMalte** [onesky/plugin-intellij#5]
Observed behaviour:
- Synchronising languages (sv, da, fr, it, nl, es, pt-BR, es, de) downloads the files but cannot write them afterwards.
- Fails with IncorrectOperationException: Cannot create file '[...]/app/src/main/res/values-pt-rBR'. File already exists.

Desired behaviour:
- Oberwrite the existing file

**Comment by bretdabaker** [comment]
Sorry for late reply, fixed in [this release](https://plugins.jetbrains.com/update/index?pr=&updateId=20854).
