### ISSUE TITLE
translated files with duplicated content

### ISSUE THREAD

**Issue by blazmag** [onesky/plugin-intellij#9]
Hi,

Our project structure is split into more than 20 different english string xml files (example : strings_account.xml, strings_dialogs.xml, string_errors.xml, etc)

If I upload all these files via the Send Strings AS action, they are correctly uploaded as separate files to the OneSky web interface. 

When I translate them on the web interface, and I download them via the web interface I get a zip file with the same amount of zipped separate files as expected, containing correctly translated strings. 

If I however try to do a sync via AS, it creates the separate files, however they all have the same content copied in them (from one of the translated files). for example:  strings_account.xml, strings_dialogs.xml, string_errors.xml will all contain strings from strings_account.xml

If I try syncing three times, it will eventually download the correct strings. 
Any idea how to avoid this? Is there also a way to disable copying over comments ? (if I translate just one of the strings, I end up with a file filled with comments and one translation) 

Thanks! 

AS version 1.4 beta 4

**Comment by bretdabaker** [comment]
Fixed in [v1.3.3](https://plugins.jetbrains.com/update/index?pr=&updateId=21473). Thanks for reporting.
